// Catálogo global de exercícios disponíveis para importar em "Meus Exercícios".
// muscleGroup: peito, costas, pernas, gluteos, ombros, biceps, triceps, abdomen, panturrilha, cardio
// equipment:   barra, halteres, maquina, cabo, peso_corporal, kettlebell, cardio
// pose:        chave do desenho de referência (ver POSE_ART em public/app.js)

const CATALOG = [
  // ---------- Peito ----------
  { key: 'supino_reto_barra', name: 'Supino reto com barra', muscleGroup: 'peito', equipment: 'barra', type: 'weight', sets: 4, pose: 'press',
    description: 'Deitado no banco reto, desça a barra até tocar levemente o peito e empurre de volta até a extensão quase completa dos cotovelos. Mantenha os ombros presos ao banco e os pés firmes no chão.' },
  { key: 'supino_inclinado_barra', name: 'Supino inclinado com barra', muscleGroup: 'peito', equipment: 'barra', type: 'weight', sets: 4, pose: 'press',
    description: 'No banco inclinado (30-45°), desça a barra em direção à parte superior do peito e empurre para cima. Foca a porção superior do peitoral.' },
  { key: 'supino_reto_halteres', name: 'Supino reto com halteres', muscleGroup: 'peito', equipment: 'halteres', type: 'weight', sets: 4, pose: 'press',
    description: 'Deitado no banco, empurre os halteres para cima até quase encostarem entre si, controlando a descida até a altura do peito.' },
  { key: 'supino_inclinado_halteres', name: 'Supino inclinado com halteres', muscleGroup: 'peito', equipment: 'halteres', type: 'weight', sets: 3, pose: 'press',
    description: 'Mesmo movimento do supino com halteres, no banco inclinado, priorizando a parte superior do peitoral.' },
  { key: 'supino_maquina', name: 'Supino na máquina (chest press)', muscleGroup: 'peito', equipment: 'maquina', type: 'weight', sets: 3, pose: 'press',
    description: 'Sentado na máquina, empurre os apoios à frente até quase estender os cotovelos, sem travar as articulações, e retorne controlando o peso.' },
  { key: 'crucifixo_halteres', name: 'Crucifixo com halteres', muscleGroup: 'peito', equipment: 'halteres', type: 'weight', sets: 3, pose: 'fly',
    description: 'Deitado no banco, abra os braços em arco com leve flexão de cotovelo até sentir alongamento no peito, depois una os halteres acima do tronco.' },
  { key: 'crucifixo_maquina', name: 'Crucifixo na máquina (peck deck)', muscleGroup: 'peito', equipment: 'maquina', type: 'weight', sets: 3, pose: 'fly',
    description: 'Sentado, junte os braços à frente do peito num movimento de arco, controlando a volta até sentir alongamento.' },
  { key: 'cross_over', name: 'Crossover no cabo', muscleGroup: 'peito', equipment: 'cabo', type: 'weight', sets: 3, pose: 'fly',
    description: 'Em pé entre as polias altas, puxe os cabos num arco à frente do corpo até se cruzarem, contraindo o peito no final do movimento.' },
  { key: 'flexao_bracos', name: 'Flexão de braços (push-up)', muscleGroup: 'peito', equipment: 'peso_corporal', type: 'weight', sets: 3, note: 'reps até a falha', pose: 'press',
    description: 'Corpo reto da cabeça aos calcanhares, desça o peito próximo ao chão flexionando os cotovelos e empurre de volta à posição inicial.' },

  // ---------- Costas ----------
  { key: 'levantamento_terra', name: 'Levantamento terra', muscleGroup: 'costas', equipment: 'barra', type: 'weight', sets: 4, pose: 'hinge',
    description: 'Com a barra rente às canelas, quadril para trás e coluna neutra, levante estendendo quadril e joelhos ao mesmo tempo até ficar totalmente em pé.' },
  { key: 'terra_romeno', name: 'Levantamento terra romeno', muscleGroup: 'costas', equipment: 'barra', type: 'weight', sets: 3, pose: 'hinge',
    description: 'Com joelhos levemente flexionados, desça a barra deslizando perto das pernas dobrando o quadril, mantendo a coluna neutra, e volte estendendo o quadril.' },
  { key: 'remada_curvada', name: 'Remada curvada com barra', muscleGroup: 'costas', equipment: 'barra', type: 'weight', sets: 4, pose: 'row',
    description: 'Tronco inclinado à frente e coluna neutra, puxe a barra em direção ao abdômen apertando as escápulas, depois estenda os braços controladamente.' },
  { key: 'remada_cavalinho', name: 'Remada cavalinho (T-bar row)', muscleGroup: 'costas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'row',
    description: 'Apoiado sobre a máquina, puxe a barra em direção ao tronco contraindo as costas, controlando o retorno.' },
  { key: 'remada_baixa_cabo', name: 'Remada baixa no cabo (sentado)', muscleGroup: 'costas', equipment: 'cabo', type: 'weight', sets: 3, pose: 'row',
    description: 'Sentado com joelhos levemente flexionados, puxe o cabo até o abdômen mantendo o tronco ereto, apertando as escápulas no final.' },
  { key: 'remada_unilateral_halter', name: 'Remada unilateral com halter', muscleGroup: 'costas', equipment: 'halteres', type: 'weight', sets: 3, note: 'cada lado', pose: 'row',
    description: 'Com um joelho e uma mão apoiados no banco, puxe o halter em direção ao quadril mantendo o cotovelo próximo ao corpo.' },
  { key: 'puxada_alta', name: 'Puxada alta (lat pulldown)', muscleGroup: 'costas', equipment: 'maquina', type: 'weight', sets: 4, pose: 'pulldown',
    description: 'Sentado com as coxas presas, puxe a barra até a parte superior do peito, levando os cotovelos para baixo e para trás.' },
  { key: 'puxada_supinada', name: 'Puxada supinada (pegada inversa)', muscleGroup: 'costas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'pulldown',
    description: 'Igual à puxada alta, mas com as palmas voltadas para você — dá mais ênfase ao bíceps junto com as costas.' },
  { key: 'barra_fixa', name: 'Barra fixa (pull-up)', muscleGroup: 'costas', equipment: 'peso_corporal', type: 'weight', sets: 3, note: 'reps até a falha', pose: 'pulldown',
    description: 'Pendurado na barra com pegada pronada, puxe o corpo até o queixo passar da barra e desça controlando o movimento.' },
  { key: 'hiperextensao', name: 'Hiperextensão de lombar', muscleGroup: 'costas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'hinge',
    description: 'No banco de hiperextensão, desça o tronco flexionando o quadril e suba até alinhar o corpo, sem hiperestender a lombar no topo.' },

  // ---------- Pernas ----------
  { key: 'agachamento_livre', name: 'Agachamento livre com barra', muscleGroup: 'pernas', equipment: 'barra', type: 'weight', sets: 4, pose: 'squat',
    description: 'Barra apoiada nas costas, desça flexionando quadril e joelhos mantendo o peito erguido, até as coxas ficarem paralelas ao chão ou mais, e suba.' },
  { key: 'agachamento_frontal', name: 'Agachamento frontal', muscleGroup: 'pernas', equipment: 'barra', type: 'weight', sets: 4, pose: 'squat',
    description: 'Barra apoiada à frente sobre os ombros, mantenha o tronco mais vertical que no agachamento tradicional durante a descida e subida.' },
  { key: 'agachamento_smith', name: 'Agachamento no smith', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'squat',
    description: 'Mesmo padrão do agachamento livre, mas guiado pelos trilhos da máquina smith, o que ajuda a manter o equilíbrio.' },
  { key: 'hack_squat', name: 'Agachamento hack (hack squat)', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'squat',
    description: 'Apoiado na máquina com as costas retas, desça flexionando os joelhos e empurre de volta pelos calcanhares.' },
  { key: 'agachamento_sumo', name: 'Agachamento sumô', muscleGroup: 'pernas', equipment: 'halteres', type: 'weight', sets: 3, pose: 'squat',
    description: 'Pés bem afastados e apontados para fora, segure o peso entre as pernas e desça mantendo o tronco ereto.' },
  { key: 'leg_press', name: 'Leg press', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 4, pose: 'legpress',
    description: 'Sentado na máquina, empurre a plataforma estendendo as pernas sem travar os joelhos, controlando a volta até um ângulo confortável.' },
  { key: 'cadeira_extensora', name: 'Cadeira extensora', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'extension',
    description: 'Sentado, estenda os joelhos elevando o peso até quase travar, e desça controlando até a posição inicial. Isola o quadríceps.' },
  { key: 'mesa_flexora', name: 'Mesa flexora (leg curl deitado)', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'flexion',
    description: 'Deitado de bruços, flexione os joelhos trazendo o peso em direção aos glúteos, controlando a volta. Isola os posteriores de coxa.' },
  { key: 'cadeira_flexora', name: 'Cadeira flexora (leg curl sentado)', muscleGroup: 'pernas', equipment: 'maquina', type: 'weight', sets: 3, pose: 'flexion',
    description: 'Sentado, flexione os joelhos puxando o peso para baixo e para trás, controlando o retorno.' },
  { key: 'avanco_halteres', name: 'Avanço (lunge) com halteres', muscleGroup: 'pernas', equipment: 'halteres', type: 'weight', sets: 3, note: 'cada lado', pose: 'lunge',
    description: 'Dê um passo à frente e desça o quadril até os dois joelhos formarem ~90°, sem o joelho de trás tocar o chão, e retorne.' },
  { key: 'afundo_bulgaro', name: 'Afundo búlgaro', muscleGroup: 'pernas', equipment: 'halteres', type: 'weight', sets: 3, note: 'cada lado', pose: 'lunge',
    description: 'Com o pé de trás apoiado num banco, desça o joelho da frente até quase 90° e suba, mantendo o tronco ereto.' },
  { key: 'agachamento_kettlebell', name: 'Agachamento goblet com kettlebell', muscleGroup: 'pernas', equipment: 'kettlebell', type: 'weight', sets: 3, pose: 'squat',
    description: 'Segure o kettlebell junto ao peito e agache mantendo os cotovelos entre os joelhos e o tronco ereto.' },

  // ---------- Glúteos ----------
  { key: 'elevacao_pelvica', name: 'Elevação pélvica (hip thrust)', muscleGroup: 'gluteos', equipment: 'barra', type: 'weight', sets: 4, pose: 'hinge',
    description: 'Com as costas apoiadas num banco e a barra sobre o quadril, empurre o quadril para cima contraindo os glúteos no topo.' },
  { key: 'gluteo_cabo', name: 'Glúteo no cabo (coice/kickback)', muscleGroup: 'gluteos', equipment: 'cabo', type: 'weight', sets: 3, note: 'cada lado', pose: 'hinge',
    description: 'Com o tornozelo preso ao cabo, estenda a perna para trás contraindo o glúteo, mantendo o tronco estável.' },
  { key: 'abducao_maquina', name: 'Abdução de quadril na máquina', muscleGroup: 'gluteos', equipment: 'maquina', type: 'weight', sets: 3, pose: 'extension',
    description: 'Sentado na máquina, afaste as pernas contra a resistência, controlando o retorno.' },
  { key: 'kettlebell_swing', name: 'Kettlebell swing', muscleGroup: 'gluteos', equipment: 'kettlebell', type: 'weight', sets: 3, pose: 'hinge',
    description: 'Com o kettlebell entre as pernas, use o impulso do quadril (não os braços) para balançar o peso até a altura dos ombros.' },

  // ---------- Ombros ----------
  { key: 'desenvolvimento_militar', name: 'Desenvolvimento militar com barra', muscleGroup: 'ombros', equipment: 'barra', type: 'weight', sets: 4, pose: 'press',
    description: 'Em pé ou sentado, empurre a barra da altura dos ombros até estender os braços acima da cabeça, sem hiperestender a lombar.' },
  { key: 'desenvolvimento_halteres', name: 'Desenvolvimento com halteres', muscleGroup: 'ombros', equipment: 'halteres', type: 'weight', sets: 3, pose: 'press',
    description: 'Sentado ou em pé, empurre os halteres para cima até quase se tocarem no topo, controlando a descida até a altura dos ombros.' },
  { key: 'desenvolvimento_maquina', name: 'Desenvolvimento na máquina', muscleGroup: 'ombros', equipment: 'maquina', type: 'weight', sets: 3, pose: 'press',
    description: 'Sentado na máquina, empurre os apoios para cima até quase estender os cotovelos e retorne controlando o peso.' },
  { key: 'elevacao_lateral', name: 'Elevação lateral com halteres', muscleGroup: 'ombros', equipment: 'halteres', type: 'weight', sets: 3, pose: 'raise',
    description: 'Com leve flexão de cotovelo, eleve os halteres lateralmente até a altura dos ombros e desça controlando o movimento.' },
  { key: 'elevacao_frontal', name: 'Elevação frontal com halteres', muscleGroup: 'ombros', equipment: 'halteres', type: 'weight', sets: 3, pose: 'raise',
    description: 'Eleve o halter à frente do corpo até a altura dos ombros, controlando a descida.' },
  { key: 'remada_alta', name: 'Remada alta com barra', muscleGroup: 'ombros', equipment: 'barra', type: 'weight', sets: 3, pose: 'row',
    description: 'Puxe a barra próxima ao corpo até a altura do peito, levando os cotovelos para cima e para fora.' },
  { key: 'crucifixo_invertido', name: 'Crucifixo invertido (reverse fly)', muscleGroup: 'ombros', equipment: 'halteres', type: 'weight', sets: 3, pose: 'fly',
    description: 'Tronco inclinado à frente, abra os braços lateralmente contraindo a parte de trás dos ombros e as costas superiores.' },
  { key: 'encolhimento_ombros', name: 'Encolhimento de ombros (shrug)', muscleGroup: 'ombros', equipment: 'halteres', type: 'weight', sets: 3, pose: 'raise',
    description: 'Com halteres ao lado do corpo, eleve os ombros em direção às orelhas e desça controladamente.' },

  // ---------- Bíceps ----------
  { key: 'rosca_direta_barra', name: 'Rosca direta com barra', muscleGroup: 'biceps', equipment: 'barra', type: 'weight', sets: 3, pose: 'curl',
    description: 'Cotovelos fixos ao lado do corpo, flexione os braços elevando a barra até a altura dos ombros e desça controlando.' },
  { key: 'rosca_halteres', name: 'Rosca com halteres', muscleGroup: 'biceps', equipment: 'halteres', type: 'weight', sets: 3, pose: 'curl',
    description: 'Flexione os cotovelos elevando os halteres, girando levemente o punho no topo do movimento (supinação).' },
  { key: 'rosca_alternada', name: 'Rosca alternada com halteres', muscleGroup: 'biceps', equipment: 'halteres', type: 'weight', sets: 3, pose: 'curl',
    description: 'Igual à rosca com halteres, alternando um braço por vez enquanto o outro permanece estendido.' },
  { key: 'rosca_martelo', name: 'Rosca martelo', muscleGroup: 'biceps', equipment: 'halteres', type: 'weight', sets: 3, pose: 'curl',
    description: 'Com os punhos em posição neutra (palmas viradas uma para a outra), flexione os cotovelos elevando os halteres.' },
  { key: 'rosca_scott', name: 'Rosca Scott (banco Scott)', muscleGroup: 'biceps', equipment: 'maquina', type: 'weight', sets: 3, pose: 'curl',
    description: 'Com o braço apoiado no banco Scott, flexione o cotovelo elevando o peso sem tirar o braço do apoio.' },
  { key: 'rosca_cabo', name: 'Rosca no cabo', muscleGroup: 'biceps', equipment: 'cabo', type: 'weight', sets: 3, pose: 'curl',
    description: 'Em pé de frente para a polia baixa, flexione os cotovelos puxando a barra ou corda em direção aos ombros.' },
  { key: 'rosca_kettlebell', name: 'Rosca com kettlebell', muscleGroup: 'biceps', equipment: 'kettlebell', type: 'weight', sets: 3, pose: 'curl',
    description: 'Segure o kettlebell pela alça e flexione o cotovelo elevando o peso, como numa rosca tradicional.' },

  // ---------- Tríceps ----------
  { key: 'triceps_pulley', name: 'Tríceps no pulley (corda ou barra)', muscleGroup: 'triceps', equipment: 'cabo', type: 'weight', sets: 3, pose: 'press',
    description: 'Cotovelos fixos ao lado do corpo, estenda os braços empurrando a corda/barra para baixo e volte controlando.' },
  { key: 'triceps_testa', name: 'Tríceps testa (skull crusher)', muscleGroup: 'triceps', equipment: 'barra', type: 'weight', sets: 3, pose: 'curl',
    description: 'Deitado no banco, flexione os cotovelos descendo a barra em direção à testa e estenda de volta, mantendo os braços verticais.' },
  { key: 'triceps_frances', name: 'Tríceps francês (overhead extension)', muscleGroup: 'triceps', equipment: 'halteres', type: 'weight', sets: 3, pose: 'curl',
    description: 'Com o halter acima da cabeça, flexione os cotovelos descendo o peso atrás da nuca e estenda de volta.' },
  { key: 'mergulho_paralelas', name: 'Mergulho nas paralelas (dips)', muscleGroup: 'triceps', equipment: 'peso_corporal', type: 'weight', sets: 3, note: 'reps até a falha', pose: 'press',
    description: 'Apoiado nas barras paralelas, desça flexionando os cotovelos e empurre o corpo de volta até quase estender os braços.' },

  // ---------- Abdômen ----------
  { key: 'prancha', name: 'Prancha', muscleGroup: 'abdomen', equipment: 'peso_corporal', type: 'time', sets: 3, pose: 'plank',
    description: 'Apoiado nos antebraços e pontas dos pés, mantenha o corpo reto da cabeça aos calcanhares, sem deixar o quadril cair ou subir.' },
  { key: 'prancha_lateral', name: 'Prancha lateral', muscleGroup: 'abdomen', equipment: 'peso_corporal', type: 'time', sets: 3, note: 'cada lado', pose: 'sideplank',
    description: 'De lado, apoiado no antebraço e na lateral do pé, mantenha o corpo alinhado sem deixar o quadril cair.' },
  { key: 'abdominal_supra', name: 'Abdominal supra (crunch)', muscleGroup: 'abdomen', equipment: 'peso_corporal', type: 'time', sets: 3, note: 'segundos de esforço contínuo', pose: 'plank',
    description: 'Deitado com joelhos flexionados, eleve a parte superior do tronco contraindo o abdômen, sem puxar o pescoço com as mãos.' },
  { key: 'abdominal_maquina', name: 'Abdominal na máquina', muscleGroup: 'abdomen', equipment: 'maquina', type: 'weight', sets: 3, pose: 'plank',
    description: 'Sentado na máquina, flexione o tronco contra a resistência contraindo o abdômen, controlando a volta.' },
  { key: 'abdominal_cabo', name: 'Abdominal no cabo (cable crunch)', muscleGroup: 'abdomen', equipment: 'cabo', type: 'weight', sets: 3, pose: 'plank',
    description: 'Ajoelhado de frente para a polia alta, flexione o tronco em direção aos joelhos contraindo o abdômen.' },
  { key: 'elevacao_pernas', name: 'Elevação de pernas', muscleGroup: 'abdomen', equipment: 'peso_corporal', type: 'time', sets: 3, note: 'segundos de esforço contínuo', pose: 'plank',
    description: 'Deitado ou pendurado na barra, eleve as pernas contraindo o abdômen, controlando a descida sem balançar o corpo.' },
  { key: 'rotacao_russa', name: 'Rotação russa (Russian twist)', muscleGroup: 'abdomen', equipment: 'peso_corporal', type: 'time', sets: 3, note: 'segundos de esforço contínuo', pose: 'plank',
    description: 'Sentado com o tronco levemente inclinado para trás, gire o tronco de um lado para o outro de forma controlada.' },

  // ---------- Panturrilha ----------
  { key: 'panturrilha_em_pe', name: 'Panturrilha em pé (na máquina)', muscleGroup: 'panturrilha', equipment: 'maquina', type: 'weight', sets: 3, pose: 'calf',
    description: 'Com os ombros sob o apoio, eleve os calcanhares o máximo possível e desça até sentir o alongamento na panturrilha.' },
  { key: 'panturrilha_sentado', name: 'Panturrilha sentado', muscleGroup: 'panturrilha', equipment: 'maquina', type: 'weight', sets: 3, pose: 'calf',
    description: 'Sentado com o peso apoiado sobre os joelhos, eleve os calcanhares contraindo a panturrilha e desça controlando.' },
  { key: 'panturrilha_leg_press', name: 'Panturrilha no leg press', muscleGroup: 'panturrilha', equipment: 'maquina', type: 'weight', sets: 3, pose: 'calf',
    description: 'Na plataforma do leg press, empurre o peso apenas com a ponta dos pés, estendendo e flexionando os tornozelos.' },
  { key: 'panturrilha_barra', name: 'Panturrilha em pé com barra', muscleGroup: 'panturrilha', equipment: 'barra', type: 'weight', sets: 3, pose: 'calf',
    description: 'Com a barra apoiada nas costas, eleve os calcanhares o máximo possível e desça controlando até o alongamento.' },

  // ---------- Cardio ----------
  { key: 'bicicleta_ergometrica', name: 'Bicicleta ergométrica', muscleGroup: 'cardio', equipment: 'cardio', type: 'bike', pose: 'bike',
    description: 'Pedale em ritmo constante ou em intervalos, ajustando o nível de resistência conforme o objetivo do treino.' },
  { key: 'esteira', name: 'Esteira (caminhada/corrida)', muscleGroup: 'cardio', equipment: 'cardio', type: 'bike', pose: 'bike',
    description: 'Caminhe ou corra na esteira ajustando velocidade e inclinação conforme o ritmo desejado.' },
  { key: 'transport_eliptico', name: 'Transport (elíptico)', muscleGroup: 'cardio', equipment: 'cardio', type: 'bike', pose: 'bike',
    description: 'Movimento contínuo de braços e pernas no aparelho elíptico, de baixo impacto para as articulações.' },
  { key: 'remo_ergometro', name: 'Remo ergômetro', muscleGroup: 'cardio', equipment: 'cardio', type: 'bike', pose: 'row',
    description: 'Empurre com as pernas, incline o tronco levemente para trás e puxe a barra até o abdômen, num movimento contínuo e ritmado.' },
];

module.exports = { CATALOG };
